openapi: 3.1.0
info:
  title: Curso recomendado
  description: API para mostrar los cursos disponibles de un estudiante en base al ultimo curso matriculado
  version: "1.0"
servers:
  - url: http://localhost:8080/api
    description: Ruta base de EKS
tags:
  - name: Curso recomendado
    description: API para mostrar los cursos disponibles
paths:
  /course/next:
    post:
      tags:
        - Curso recomendado
      summary: Listado de cursos disponibles
      description: Se muestra el listado de cursos disponibles en base al ultimo curso matriculado.
      operationId: courseNext
      parameters:
        - name: codigoCurso
          in: query
          description: Codigo del ultimo curso matriculado
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Listado de cursos disponibles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CursoResponse"
              examples:
                ejemploCurso:
                  value:
                    - codigo: B02
                      nombre: Basico 2
                      categoria: Adultos y Jovenes
                    - codigo: B03
                      nombre: Basico 3
                      categoria: Adultos y Jovenes
        "404":
          description: Datos incompletos
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CursoResponseError"
              example:
                id: 404
                error: Tipo de error
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CursoResponseError"
              example:
                id: 500
                error: Tipo de error

components:
  schemas:
    CursoResponse:
      type: object
      properties:
        codigo:
          type: string
        nombre:
          type: string
        categoria:
          type: string
    CursoResponseError:
      type: object
      properties:
        id:
          type: integer
          format: int64
        error:
          type: string
